version: '3'
services:
  database:
    image: postgres:11.2
    container_name: nodejsnights-db
    environment:
      POSTGRES_DB: nodejsnights
    ports:
      - 5432:5432

  database_tests:
    image: postgres:11.2
    container_name: nodejsnights-db-tests
    environment:
      POSTGRES_DB: nodejsnights-db-tests
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: testpasswd

    ports:
      - 5433:5432
